---
# PHP Coding Standards Fixer: http://cs.sensiolabs.org/
# Installation documentation: https://github.com/fabpot/PHP-CS-Fixer
#

- name: Download and install php-cs-fixer to /usr/local/bin (Global installation)
  get_url:
    url: " {{ url }}"
    dest: "/usr/local/bin/php-cs-fixer"

- name: Make php-cs-fixer executable
  file:
    path=/usr/local/bin/php-cs-fixer
    state=file
    mode=0755

- name: Update php-cs-fixer
  command:
    php-cs-fixer self-update
  register: php_cs_fixer_update
  changed_when: "'updated' in php_cs_fixer_update.stdout"
